chore: refine e2e test (#884)
* chore: refine e2e test

* chore: check pr test

* chore: fix Unrecognized named-value env

* chore: fix trigger terraform-init-eks

* chore: fix trigger e2e test

* chore: fix check pr make test

* chore: fix  No Docker tag has been generated. Check tags input

* chore: fix install aperag

* chore: upgrade kb version

* chore: delete e2e-test-parallel.yml

* chore: delete e2e-test.yml

diff --git a/.github/workflows/cicd-pull-request.yml b/.github/workflows/cicd-pull-request.yml
--- a/.github/workflows/cicd-pull-request.yml
+++ b/.github/workflows/cicd-pull-request.yml
@@ -41,6 +41,7 @@ jobs:
   make-test:
     needs: trigger-mode
     runs-on: ubuntu-latest
+    if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
     steps:
       - uses: actions/checkout@v4
       - name: Setup Python
@@ -101,14 +102,19 @@ jobs:
       APECD_REF: "v0.1.48"
     secrets: inherit
 
+  e2e-test:
+    if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
+    needs: trigger-mode
+    uses: ./.github/workflows/e2e-aperag.yml
+    secrets: inherit
+
   pr-check:
-    name: make test
-    needs: [ trigger-mode, make-test, check-image, check-frontend-image, check-helm ]
+    name: PR Check
+    needs: [ trigger-mode, make-test, check-image, check-frontend-image, check-helm, e2e-test ]
     if: ${{ github.event.review.state == 'approved' && always() }}
     runs-on: ubuntu-latest
     steps:
       - name: make test check
-        if: github.event.pull_request.head.repo.full_name != github.repository
         run: |
           if [[ "${{ needs.make-test.result }}" == "failure" || "${{ needs.make-test.result }}" == "cancelled" ]]; then
               echo "make test fail"
@@ -132,6 +138,13 @@ jobs:
       - name: release helm check
         run: |
           if [[ "${{ needs.check-helm.result }}" == "failure" || "${{ needs.check-helm.result }}" == "cancelled" ]]; then
+              echo "release helm fail"
+              exit 1
+          fi
+
+      - name: e2e test check
+        run: |
+          if [[ "${{ needs.e2e-test.result }}" == "failure" || "${{ needs.e2e-test.result }}" == "cancelled" ]]; then
               echo "release helm fail"
               exit 1
           fi
