chore: kubechat e2e test workflow

diff --git a/.github/workflows/release-image.yml b/.github/workflows/release-image.yml
--- a/.github/workflows/release-image.yml
+++ b/.github/workflows/release-image.yml
@@ -38,6 +38,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       tag-name: ${{ steps.get_tag_name.outputs.tag_name }}
+      artifact-key: ${{ steps.get_tag_name.outputs.artifact_key }}
     steps:
       - name: Get Tag Name
         id: get_tag_name
@@ -47,6 +48,8 @@ jobs:
               TAG_NAME="${{ env.RELEASE_VERSION }}"
           fi
           echo tag_name=$TAG_NAME >> $GITHUB_OUTPUT
+          ARTIFACT_KEY="${{ env.RELEASE_VERSION }}-image"
+          echo 'artifact_key='${ARTIFACT_KEY} >> $GITHUB_OUTPUT
 
   release-kubechat-image:
     if: ${{ github.event.action == 'published' || inputs.image_name == '' || inputs.image_name == 'kubechat' }}
@@ -84,9 +87,18 @@ jobs:
       ENABLE: "disable"
     secrets: inherit
 
+  delete-actions-cache:
+    if: ${{ always() }}
+    needs: [ image-tag ]
+    uses: apecloud/apecloud-cd/.github/workflows/delete-actions-cache.yml@v0.1.41
+    with:
+      CACHE_KEY: "${{ needs.image-tag.outputs.artifact-key }}"
+      APECD_REF: "v0.1.41"
+    secrets: inherit
+
   release-result:
     runs-on: ubuntu-latest
-    needs: [ release-kubechat-image, release-kubechat-llmserver-image ]
+    needs: [ delete-actions-cache, release-kubechat-image, release-kubechat-llmserver-image ]
     if: ${{ always() && github.event.action == 'published' }}
     outputs:
       release-result: ${{ steps.get_release_result.outputs.release_result }}
@@ -94,11 +106,26 @@ jobs:
       - name: get release result
         id: get_release_result
         run: |
+          ARTIFACT_KEY="${{ env.RELEASE_VERSION }}-image"
+          touch ${ARTIFACT_KEY}
+          echo 'artifact_key='${ARTIFACT_KEY} >> $GITHUB_OUTPUT
+          
           RELEASE_RESULT="error"
           if [[ "${{ needs.release-kubechat-image.result }}" == "success" && "${{ needs.release-kubechat-llmserver-image.result }}" == "success" ]]; then
               RELEASE_RESULT="success"
+              echo "success" > ${ARTIFACT_KEY}
+          else
+              echo "error" > ${ARTIFACT_KEY}
           fi
           echo 'release_result='$RELEASE_RESULT >> $GITHUB_OUTPUT
+
+      - name: Save Artifact
+        id: cache-artifact-save
+        uses: actions/cache/save@v3
+        with:
+          path: |
+            ${{ steps.get_release_result.outputs.artifact_key }}
+          key: ${{ steps.get_release_result.outputs.artifact_key }}
 
   send-message:
     needs: [ image-tag, release-result ]
@@ -108,4 +135,38 @@ jobs:
       TYPE: "2"
       CONTENT: "release image ${{ needs.image-tag.outputs.tag-name }} ${{ needs.release-result.outputs.release-result }}"
       APECD_REF: "v0.1.36"
+    secrets: inherit
+
+  check-result:
+    if: github.event.action == 'published'
+    needs: [ release-result ]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        type: [image, chart]
+    steps:
+      - name: Restore ${{ matrix.type }} Artifact
+        id: cache-artifact-restore
+        uses: actions/cache/restore@v3
+        with:
+          path: |
+            ${{ env.RELEASE_VERSION }}-${{ matrix.type }}
+          key: ${{ env.RELEASE_VERSION }}-${{ matrix.type }}
+
+      - name: check release result
+        run: |
+          release_result=$( cat ${{ env.RELEASE_VERSION }}-${{ matrix.type }} )
+          if [[ "$release_result" != "success" ]]; then
+              exit 1
+          fi
+
+  e2e-kubechat:
+    needs: [ image-tag, release-result, check-result ]
+    uses: apecloud/apecloud-cd/.github/workflows/trigger-workflow.yml@v0.1.41
+    with:
+      GITHUB_REPO: "apecloud/kubechat"
+      BRANCH_NAME: "main"
+      WORKFLOW_ID: "e2e-kubechat.yml"
+      VERSION: "${{ needs.image-tag.outputs.tag-name }}"
+      APECD_REF: "v0.1.41"
     secrets: inherit
